/gary/lidar/front/ydlidar_driver_front:
  ros__parameters:
    port: /dev/serial/by-path/platform-3610000.xhci-usb-0:4.3.1:1.0-port0

/gary/lidar/back/ydlidar_driver_back:
  ros__parameters:
    port: /dev/serial/by-path/platform-3610000.xhci-usb-0:4.3.4:1.0-port0
