/gary/nav/rtabmap/rtabmap:
  ros__parameters:
    landmark_angular_variance: 0.01
    Vis/EstimationType: "2"
    RGBD/NeighborLinkRefining: "True"
    Icp/MaxTranslation: "1"
    Icp/MaxRotation: "0.78"
    Icp/Iterations: "50"
    Icp/MaxCorrespondenceDistance: "0.5"
    Icp/CorrespondenceRatio: "0.1"
    RGBD/OptimizeMaxError: "0"
    Optimizer/Strategy: "1"
    Optimizer/Robust: "False"
    Reg/Force3DoF: "true"
    Reg/Strategy: "1"
    max_obstacle_height: "2.0"
    proj_max_ground_height: "0.1"
    proj_max_height: "2.0"
    Grid/MaxObstacleHeight: "1.7"
    Grid/MinObstacleHeight: "0.2"
    Grid/RangeMax: "8.0"
    Grid/CellSize: "0.02"
    rgbd_cameras: 1
    subscribe_depth: False
    subscribe_rgbd: False
    subscribe_rgb: False
    subscribe_stereo: False
    subscribe_scan: True
    subscribe_scan_cloud: False
    subscribe_user_data: False
    subscribe_odom_info: False
    frame_id: "base_link"
    map_frame_id: "map"
    odom_frame_id: "odom_offset"
    publish_tf: True
    ground_truth_frame_id: ""
    ground_truth_base_frame_id: ""
    odom_tf_angular_variance: 0.0001
    odom_tf_linear_variance: 0.0001
    odom_sensor_sync: False
    wait_for_transform: 0.2
    approx_sync: True
    queue_size: 10
    qos_image: 2
    qos_scan: 2
    qos_odom: 2
    qos_camera_info: 2
    qos_imu: 2
    qos_gps: 2
    qos_user_data: 2
    scan_normal_k: "0"
    landmark_linear_variance: 0.0001
    Mem/IncrementalMemory: "False"
    Mem/InitWMWithAllNodes: "True"
